name: media_source
description: A new Dart package project.
version: 0.1.0-alpha.1

repository: https://github.com/hossameldinmi/media_source

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  cross_file: ^0.3.4+2
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_media_metadata: ^1.0.0+1
  mime: ^2.0.0
  path: ^1.9.1
  path_provider: ^2.1.5
  sized_file: ^1.3.3
  uuid: ^4.5.1
  web: ^1.1.1

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
