name: media_source
description: A new Dart package project.
version: 0.2.0-alpha.2

repository: https://github.com/hossameldinmi/media_source

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  cross_file: ^0.3.4+2
  equatable: ^2.0.7
  file_type_plus: ^1.0.0
  flutter:
    sdk: flutter
  path: ^1.9.1
  sized_file: ^1.3.3
  uuid: ^4.5.1
  web: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  lints: ^3.0.0
