name: media_source
version: 1.0.0

description: Type-safe, cross-platform media handling for files, memory, asset, and network sources with automatic type detection, seamless conversions, and Flutter integration.

repository: https://github.com/hossameldinmi/media_source
homepage: https://github.com/hossameldinmi/media_source


topics:
  - media
  - media-type
  - files
  - storage
  - file-type

screenshots:
  - description: The media_source package logo.
    path: assets/icon.png

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  cross_file: ^0.3.4+2
  equatable: ^2.0.7
  file_type_plus: ^1.0.0
  flutter:
    sdk: flutter
  path: ^1.9.0
  file_sized: ^2.0.0
  web: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  lints: ^3.0.0
